### ISSUE TITLE
bit more verbose data and examples to help explain each function ?

### ISSUE THREAD

**Issue by joeblew99** [orcaman/financial#3]
I knwo its early days but if its possible to put some data examples with some background on the logic / use case if would really help me.

**Comment by orcaman** [comment]
Hi @joeblew99,

I added some examples for both the NPV and IRR functions, see updated readme with GoDoc links. 

As for the background, you are welcome to read this: https://medium.com/@_orcaman/package-financial-for-golang-the-math-behind-the-irr-function-1eedf225d9f

Cheers,
Or

**Comment by joeblew99** [comment]
@orcaman thank you.

Will have a play
